[package]
name = "readability"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive", "wrap_help", "color"] }
coherity = { version = "0.1.1", path = "../coherity" }
